name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      REPO_OWNER_LOWER: ${{ github.repository_owner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        
      - name: gradlew bootJar
        run: ./gradlew bootJar
        
      - name: List files in build directory
        run: ls -R build/libs
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ONEEAT_TOKEN }}
          
      - name: Convert repository owner to lowercase
        run: echo "REPO_OWNER_LOWER=${REPO_OWNER_LOWER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/oneeat/my-app:${{ github.sha }},ghcr.io/${{ env.REPO_OWNER_LOWER }}/oneeat/my-app:latest
          build-args: |
            API_KEY=${{ secrets.API_KEY }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }}

      - name: Run Docker container on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo ${{ secrets.ONEEAT_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ env.REPO_OWNER_LOWER }}/oneeat/my-app:latest
            docker stop my-app-container || true
            docker rm my-app-container || true
            docker run -d --name my-app-container \
              -p 8080:8080 \
              -e API_KEY=${{ secrets.API_KEY }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              -e KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }} \
              ghcr.io/${{ env.REPO_OWNER_LOWER }}/oneeat/my-app:latest
